# Change these first
owner: TogijorOK # Your GitHub organization or username, where this repository lives
repo: Monitor_WEB # The name of this repository

sites:
  
  - name: WEB-AySA
    url: https://www.aysa.com.ar
  - name: Intranet
    url: https://intranet.aysa.com.ar
  - name: Servicedesk
    url: https://servicedesk.aysa.com.ar
  - name: Turnera
    url: https://turnosonline.aysa.com.ar/
  - name: Campus
    url: https://campus.aysa.com.ar
  - name: Correo
    url: https://mail.aysa.com.ar
    
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /Monitor_WEB
  logoUrl: https://www.aysa.com.ar/media-library/imagenes_inicio/logo.png
  href: https://www.aysa.com.ar
  name: Soporte Aplicativos
  introTitle: "**MONITOR-Servicios WEB**"
  introMessage: Dirección Tecnología de la Información - Gerencia de Servicios Informáticos
  navbar:
    - title: Estado de sevicios
      href: /
    - title: AySA
      href: https://www.aysa.com.ar

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
